[functions]
directory = "netlify/functions/"

Explicitly allow the Netlify bundler to use these modules in the function environment
external_node_modules = ["node-fetch"]
node_bundler = "esbuild"

[build]
node_version = "20"